Added error checking to check if 'xrandr' is installed and code cleanup

diff --git a/.config/scripts/xrandr-cli b/.config/scripts/xrandr-cli
--- a/.config/scripts/xrandr-cli
+++ b/.config/scripts/xrandr-cli
@@ -1,12 +1,22 @@
-#!/bin/bash
+#!/bin/sh
 # ------------------------------------------------
 # Script Name    - xrandr-cli
 # Author Name    - Smeueg
 # Author Email   - Smeueg@gmail.com
 # Author Gitlab  - https://gitlab.com/Smeueg
-# Last Updated   - Tue 12 Apr 16:46:36 WIB 2022
+# Last Updated   - Sun  1 May 2022
+# ------------------------------------------------
+
 # ------------------------------------------------
 # Script to interactively change the resolution using xrandr
+
+if ! [ "$(command -v xrandr)" ]; then do
+	printf "[\033[1;31mERROR\033[0m] The command 'xrandr' not found, exiting\n" 2>&1
+	exit 1
+fi
+
+
+
 xrandr_output=$(xrandr)
 newline="
 "
@@ -28,12 +38,12 @@ if [ "${BASH_NAME}" ]; then
 	read_char() { read -n1 input; }
 else
 	if ! [ "$(command -v stty)" ]; then
-		printf "\033[31m\033[1m[ERROR]\033[0m The command 'stty' not found, exiting"
+		printf "[\033[31m\033[1mERROR\033[0m] The command 'stty' not found, exiting\n" 2>&1
 		exit 1
 	fi
 
 	if ! [ "$(command -v dd)" ]; then
-		printf "\033[31m\033[1m[ERROR]\033[0m The command 'dd' not found, exiting"
+		printf "[\033[31m\033[1mERROR\033[0m] The command 'dd' not found, exiting\n" 2>&1
 		exit 1
 	fi
 
@@ -41,8 +51,8 @@ else
 	trap "stty '${stty_settings}'; exit 1" INT
 	stty -icanon
 	read_char() {
-		input="$(dd bs=1 count=1 2>&1)"
-		input="${input%${input#?}}"
+		input=$(dd bs=1 count=1 2>&1)
+		input=${input%${input#?}}
 	}
 fi
 
@@ -98,7 +108,7 @@ loop() {
 			"j") [ ${chosen} -ne $((i - 1)) ] && chosen=$((chosen + 1));;
 			"k") [ ${chosen} -ne 0 ] && chosen=$((chosen - 1));;
 			"q") [ "${stty_settings+x}" ] && stty "${stty_settings}"
-				 exit 0;;
+				exit 0;;
 			""|" "|"${newline}")
 				printf "\033[$((i+2))A\r\033[J"
 				IFS=${newline} pick "${2}" "${3}"
