update

diff --git a/.local/bin/droidcam-start b/.local/bin/droidcam-start
--- a/.local/bin/droidcam-start
+++ b/.local/bin/droidcam-start
@@ -8,6 +8,14 @@ video=true
 audio=false
 
 
+Kill() {
+	if printf '%s' "${arguments}" | grep kill >/dev/null; then
+		killall droidcam-cli
+		exit
+	fi
+}
+
+
 ModuleExists() {
 	moduleName="$1"
 	! modinfo $moduleName 2>&1 | grep "ERROR: Module $moduleName not found" >/dev/null
@@ -39,7 +47,10 @@ LoadModules() {
 		done
 
 		cmd="su -c '${cmd}'"
-		eval "${cmd}"
+		if ! eval "${cmd}"; then
+			printf "Wrong password"
+			exit
+		fi
 	fi
 
 
@@ -50,11 +61,11 @@ LoadPulseaudioModule() {
 	printf '\n-------------\n\n'
 	printf 'Loading pulseaudio module...\n'
 	if pactl list | grep droidcam_audio >/dev/null; then
-		printf 'Pulseaudio module is already loaded, skipping...\n'
+		printf 'Pulseaudio module is already loaded, skipping...'
 	else
 		pactl load-module module-alsa-source device=hw:Loopback,1,0 source_properties=device.description=droidcam_audio >/dev/null &&
-			printf 'Loaded pulseaudio module\n' ||
-			printf 'Failed to load pulseaudio module\n'
+			printf ' Loaded\n' ||
+			printf ' Failed\n'
 	fi
 
 	pactl list | grep droidcam_audio >/dev/null &&
@@ -92,6 +103,8 @@ main() {
 		exit
 	fi
 
+	Kill
+
 	if HandleArg '\-a' 'snd_aloop';    then audio=true; video=false; fi
 	if HandleArg '\-v' 'v4l2loopback'; then             video=true; fi
 
@@ -105,7 +118,7 @@ main() {
 	${audio} && sleep 2 && LoadPulseaudioModule
 
 	tput bold
-	printf 'Run `killall droidcam-cli` to stop droidcam\n'
+	printf 'Run `droidcam-start kill` or `killall droidcam-cli` to stop droidcam\n'
 	tput sgr0
 }
 main
diff --git a/.local/bin/migrate/mine-music b/.local/bin/migrate/mine-music
--- a/.local/bin/migrate/mine-music
+++ b/.local/bin/migrate/mine-music
@@ -1,33 +1,79 @@
 #!/bin/sh
-# These songs take about 1GB of space
+# Downloads my personal favorite songs/albums
+# These songs take alot of space
+
+printf 'NOTICE: I DO NOT OWN ANY OF THIS MUSIC, CREDIT GOES TO THEIR RESPECTIVE ARTIST/BANDS/MUSICIANS\n'
 
 urls="
-https://www.youtube.com/watch?v=QAOBbPnI5-g
-https://www.youtube.com/watch?v=QBJ1OzMtNwg
-https://www.youtube.com/watch?v=aMH7yp1EXw8
+https://www.youtube.com/watch?v=QAOBbPnI5-g   Metallica - Master Of Puppets
+https://www.youtube.com/watch?v=QBJ1OzMtNwg   Metallica - Ride The Lightning
+https://www.youtube.com/watch?v=aMH7yp1EXw8   Metallica - And Justice For All
+https://www.youtube.com/watch?v=a41bERTFBUI   Metallica - Ecstacy Of Gold
+https://www.youtube.com/watch?v=c8qrwON1-zE   Metallica - Orion
+https://www.youtube.com/watch?v=_t6-KdRwC_U   Equilibrium - Kurzes Epos
+https://www.youtube.com/watch?v=LJRf19VcwUU   Equilibrium - Aufbruch
+https://www.youtube.com/watch?v=qQU4vatuT6g   Equilibrium - Mana
+https://www.youtube.com/watch?v=7-i-LhRudP4   Stratovarius - Stratofortress
+https://www.youtube.com/watch?v=KHVP2anxbH8   Stratovarius - Holy Light
+https://www.youtube.com/watch?v=aJZJVtBPl_E   Tiluland - Axes Of The Universe
+https://www.youtube.com/watch?v=7elDoQMH48k   Savatage - The Storm
+https://www.youtube.com/watch?v=HOVQ2fkQI5A   Running Wild - Siberian Winter
+https://www.youtube.com/watch?v=-uRmn0aUMK4   Exmortus - Moonlight Sonata (Act 3)
+https://www.youtube.com/watch?v=tBdtJzeCkJ4   Ascension - Orb of the Moons
+https://www.youtube.com/watch?v=4xAu2Ay15fs   Galneryus - Vetelgyus
+https://www.youtube.com/watch?v=9XlNbQv_Rg4   Warmen - Salieri Strikes Back
+https://www.youtube.com/watch?v=JGv6gzImsfg   Cain's Offering - I Am Legion (Instrumental)
+https://www.youtube.com/watch?v=r8n6j21UJMo   Dark Forest - Heart of the Rose
 "
 
-currentDir=$PWD
-dir=$HOME/Music
+currentDir=${PWD}
+dir=${HOME}/Music
 
-
-if ! command -v youtube-dl >/dev/null; then
-	printf "Getting youtube-dl\n"
-	if command -v curl >/dev/null; then
-		cmd="$(curl -L https://yt-dl.org/downloads/latest/youtube-dl)"
-	elif command -v wget >/dev/null; then
-		cmd="$(wget https://yt-dl.org/downloads/latest/youtube-dl)"
+GetYTDL() {
+	if ! command -v youtube-dl >/dev/null; then
+		printf "'youtube-dl' is not installed, getting youtube-dl\n"
+		if command -v curl >/dev/null; then
+			cmd="$(curl -L https://yt-dl.org/downloads/latest/youtube-dl)"
+		elif command -v wget >/dev/null; then
+			cmd="$(wget https://yt-dl.org/downloads/latest/youtube-dl)"
+		else
+			printf 'Cannot download youtube-dl, curl and wget is not installed...\n'
+			exit
+		fi
 	else
-		printf 'Cannot download youtube-dl, curl and wget is not installed...\n'
-		exit
+		cmd="$(< $(which youtube-dl))"
 	fi
-else
-	cmd="$(cat $(which youtube-dl))"
-fi
+}
 
 
-[ ! -d "$dir" ] && mkdir --parents "$dir"
-cd "$dir"
+main() {
+	GetYTDL
 
-echo "$urls" | xargs -I {} python -c "$cmd" '{}' -o "./%(title)s.%(ext)s"
-cd "$currentDir"
+	[ ! -d "${dir}" ] && mkdir --parents "${dir}"
+	cd "${dir}"
+
+	for url in ${urls}; do
+
+		case ${url} in
+			https*) ;;
+			*) continue ;;
+		esac
+
+
+		title=$(printf "${urls}" | grep -w "${url}")
+		title=${title##$url}
+		title=${title#${title%%[![:space:]]*}}
+
+		if [ ! -f "${dir}/${title}.mp3" ]; then
+			printf 'Downloading %s... ' "${title}"
+			python -c "${cmd}" --extract-audio --audio-format mp3 "${url}" -o "./${title}.mp3" &&
+				printf 'Success\n' ||
+				printf 'Failed\n'
+		else
+			printf '%s.mp3 exists, skipping...\n' "${title}"
+		fi
+	done
+
+	cd "${currentDir}"
+}
+main
diff --git a/.local/bin/screenshot b/.local/bin/screenshot
--- a/.local/bin/screenshot
+++ b/.local/bin/screenshot
@@ -1,65 +1,167 @@
 #!/bin/sh
-if [ "$1" == "-t" ]; then
-	dir="/tmp/TmpScreenshots/"
-	tmpmsg="in /tmp/TmpScreenshots"
-	shift
-else
-	dir="$HOME/Pictures/Screenshots"
-	tmpmsg=""
-fi
+DIRECTORY="${1:-$HOME/Pictures/Screenshots}"
+IMG_PATH="${DIRECTORY%/}/Screenshot_$(date '+%Y-%m-%d-(%H:%M:%S)').png"
+SUCCESS_MSG="Saved screenshot in ${IMG_PATH}"
+FAILED_MSG="Failed to save screenshot in ${IMG_PATH}"
 
-checkDir(){
-	[ ! -d "$dir" ] && mkdir --parents "$dir"
+[ -t 0 ] &&
+	USING_TERMINAL=true  ||
+	USING_TERMINAL=false
+
+notify() {
+	if ! ${USING_TERMINAL}; then
+		if [ -n "$(command -v herbe)" ]; then
+			herbe "${1}"
+		else
+			printf 'ERROR: `herbe` is not installed\n'
+			printf '%b\n' "${1}"
+		fi
+	else
+		printf '%b\n' "${1}"
+	fi
 }
 
 
-CMD=$(echo -e "Full Screenshot\nPartial Screenshot\nCancel" | dmenu "$@" | cut -d' ' -f1);
-Current_Date=$(date '+%Y_%m_%d-(%H:%M:%S)')
+check_dir() {
+	[ ! -d "${DIRECTORY}" ] && mkdir "${DIRECTORY}" ||
+		notify 'Failed to create DIRECTORY' && exit
+}
 
-path="$dir/Screenshot_${Current_Date}.png"
-string="Took Screenshot Screenshot_${Current_Date}.png ${tmpmsg}"
+
+picker() {
+	if ! ${USING_TERMINAL}; then
+		if [ -n "$(command -v dmenu)" ]; then
+			printf 'Full\nPartial\nCancel\n' | dmenu -p 'Type of screenshot'
+		else
+			${TERMINAL} -e $0
+		fi
+	elif [ -n "$(command -v fzf)" ]; then
+		printf 'Cancel\nPartial\nFull\n' | fzf --height 5
+		return
+	fi
 
 
-scrot_screenshot(){
-	case $CMD in
+	if [ -n "${BASH_VERSION}" ]; then
+		get_key='read -n1 key'
+	elif [ -n "${ZSH_VERSION}" ]; then
+		get_key='read -k1 key'
+	elif [ -n "$(command -v stty)" ] && [ -n "$(command -v dd)" ]; then
+		stty_old=$(stty -g)
+		stty -icanon -echo
+
+		esc=$(printf '\033')
+		get_key='key=$(dd ibs=1 count=1 2>/dev/null)'
+	else
+		notify 'ERROR: Dependencies not met (bash is not installed, zsh is not installed, stty and dd is not installed)'
+		exit
+	fi
+
+
+	index=0
+	string="Full 0\nPartial 1\nCancel 2\n"
+	while true; do
+		printf 'Select type of screenshot:\n' >&2
+		printf '%b' "${string}" | while read line; do
+			[ "${line##* }" -eq ${index} ] &&
+				printf '\033[7m%s\033[0m\n' "${line%% ?}" >&2 ||
+				printf '%s\n' "${line%% ?}" >&2
+		done
+		printf '\n' >&2
+
+		eval "${get_key}"
+		if [ -z "${key#$'\n'}" ] || [ "${key}" = " " ]; then
+			printf '\033[1F' >&2
+			printf '\033[1F' >&2
+			printf '\033[1F' >&2
+			printf '\033[1F' >&2
+			printf '\033[1F' >&2
+			printf '\033[1F' >&2
+			printf '\033[0J' >&2
+
+			printf '%b' "${string}" | while read line; do
+				[ "${line##* }" -eq ${index} ] &&
+					printf '%s\n' "${line%% ?}"
+			done
+			break
+		fi
+
+		case ${key}${esc:-0} in
+			k?|A1) [ ${index} -ne 0 ] && index=$((index - 1)) ;;
+			j?|B1) [ ${index} -ne 2 ] && index=$((index + 1)) ;;
+			q?) return ;;
+			${esc}*|'['?) esc=1;;
+			*) esc=0;;
+		esac
+
+		printf '\033[1F' >&2
+		printf '\033[1F' >&2
+		printf '\033[1F' >&2
+		printf '\033[1F' >&2
+		printf '\033[1F' >&2
+		printf '\033[1F' >&2
+	done
+
+	[ -n "${stty_old}" ] &&
+		stty "${stty_old}"
+}
+
+
+use_scrot() {
+	read input
+	case "${input}" in
 		Full)
-			checkDir
-			scrot -d 0.5 "$path" &&
-			herbe "$string"
+			scrot -d 0.5 "${IMG_PATH}" &&
+				(notify "${SUCCESS_MSG}"; true) ||
+				notify "${FAILED_MSG}"
 			;;
 
 		Partial)
-			checkDir
-			scrot -s -d 0.5 "$path" &&
-			herbe "$string"
+			scrot -s -d 0.5 "${IMG_PATH}" &&
+				(notify "${SUCCESS_MSG}"; true) ||
+				notify "${FAILED_MSG}"
 			;;
 
-		*) herbe "Did not take screenshot";
+		*)
+			notify 'Did not take screenshot'
+			;;
 	esac
+
 }
 
-imagemagick_screenshot(){
-	case $CMD in
+use_magick() {
+	read input
+
+	case "${input}" in
 		Full)
-			checkDir
-			sleep 0.5 && magick import -window root "$path" &&
-			herbe "$string"
+			sleep 0.5
+			magick import -window root "${IMG_PATH}" &&
+				(notify "${SUCCESS_MSG}"; true) ||
+				notify "${FAILED_MSG}"
 			;;
 
 		Partial)
-			checkDir
-			sleep 0.5 && magick import "$path" &&
-			herbe "$string"
+			sleep 0.5
+			magick import "${IMG_PATH}" &&
+				(notify "${SUCCESS_MSG}"; true) ||
+				notify "${FAILED_MSG}"
 			;;
-		*) herbe "Did not take screenshot";
+
+		*)
+			notify "Did not take screenshot"
+			;;
 	esac
 }
 
 
-if command -v scrot; then
-    scrot_screenshot
-elif command -v magick; then
-    imagemagick_screenshot
-else
-    herbe "You do not have either scrot or imagemagick installed"
-fi
+main() {
+	if [ -z "${DISPLAY}" ]; then
+		notify 'ERROR: Cannot open display, you are either running this in the tty or in wayland. Both are not yet supported...\n'
+	elif [ -n "$(command -v magick)" ]; then
+		picker | use_magick
+	elif [ -n "$(command -v scrot)" ]; then
+		picker | use_scrot
+	else
+		printf '`magick` and `scrot` are not installed, please install one of them...\n'
+	fi
+}
+main
