Dotfiles update

diff --git a/.config/shellconfig/main_rc b/.config/shellconfig/main_rc
--- a/.config/shellconfig/main_rc
+++ b/.config/shellconfig/main_rc
@@ -125,58 +125,31 @@ compress_documents() {
 }
 
 
-record() {
-	# Record desktop screen and desktop audio
-	if ! [ "${1}" ]; then
-		printf "[\033[1;31mERROR\033[0m]: Filename not provided\n" >&2
-		return 1
-	fi
-
-	if ! [ "$(pidof pulseaudio)" ]; then
-		printf "[\033[1;31mERROR\033[0m]: Pulseaudio isn't running\n" >&2
-		return 1
-	fi
-
-	for dep in "pactl" "ffmpeg"; do
-		[ "$(command -v ${dep})" ] && continue
-		printf "[\033[1;31mERROR\033[0m]: Command '${dep}' not found\n" >&2
-		return 1
-	done
-
-	tab=$(printf '\t')
-	source=$(pactl list short sources | { read line; printf '%s\n' "${line}"; })
-	source=${source#*${tab}}
-	source=${source%%${tab}*}
-	ffmpeg \
-		-f x11grab \
-		-framerate 30 \
-		-i :0.0 \
-		-f pulse \
-		-i "${source}" \
-		-preset ultrafast \
-		-crf 18 \
-		-pix_fmt yuv420p "${1}"
-}
-
-
 colors() {
+	# Print terminal colors
+	if ! [ "${1##*[!0-9]*}" ]; then
+		printf "[\033[1;31mERROR\033[0m]: Not an integer\n" >&2
+		return 1
+	elif [ ${1} -gt 255 ]; then
+		printf "[\033[1;31mERROR\033[0m]: Number is greater than 255\n" >&2
+		return 1
+	fi
+
 	i=0
-	printf '\n'
 	case "${1}" in
-		"255")
-			while [ ${i} -ne 255 ]; do
-				printf "\033[7m\033[38;5;${i}m ${i} \033[0m"
-				i=$((i + 1))
-			done
-			;;
-		"16")
-			while [ ${i} -ne 16 ]; do
-				[ ${i} -eq 8 ] && printf '\n\n'
-				printf "\033[7m\033[38;5;${i}m  \033[0m "
-				i=$((i + 1))
-			done
-			printf '\n'
-			;;
+		"16") printf '\n'
+			  while [ ${i} -ne 16 ]; do
+				  [ ${i} -eq 8 ] && printf '\n\n'
+				  printf "\033[7m\033[38;5;${i}m  \033[0m "
+				  i=$((i + 1))
+			  done
+			  printf '\n'
+			  ;;
+		*) while [ ${i} -ne ${1} ]; do
+			   printf "\033[7m\033[38;5;${i}m ${i} \033[0m"
+			   i=$((i + 1))
+		   done
+		   ;;
 	esac
 	printf '\n'
 	unset i
