Update

diff --git a/.config/shellconfig/main_rc b/.config/shellconfig/main_rc
--- a/.config/shellconfig/main_rc
+++ b/.config/shellconfig/main_rc
@@ -38,6 +38,12 @@ print_prompt() {
 	reset="\033[0m"
 
 
+	tmp="$(tty)"
+	if ! [ "${tmp%%/dev/tty*}" ] || [ "${TERM}" = "dumb" ]; then
+		symbol=">"
+	fi
+
+
 	if [ "${BASH}" ]; then
 		wrapper_start="\001"
 		wrapper_end="\002"
@@ -130,15 +136,6 @@ dit() {
 }
 
 
-e() {
-	if [ "${EDITOR}" = "emacs" ] && [ "$(command -v emacsclient)" ]; then
-		emacsclient -a ${EDITOR} "$@" &
-	else
-		${EDITOR} "$@"
-	fi
-}
-
-
 fetsh() {
 	bin=$(command -v fet.sh)
 	if [ "${bin}" ]; then
@@ -165,8 +162,21 @@ compress_documents() {
 		printf '\033[1m\033[31m[ERROR]\033[0m "%s" does not exist, exiting.\n' "${HOME}/Documents"
 		return
 	fi
+	if [ "$(command -v tar)" ]; then
+		printf '\033[1m\033[31m[ERROR]\033[0m Command `tar` not found, exiting.\n'
+		return
+	fi
 	printf 'Compressing "%s" to %s\n' "${HOME}/Documents" "${HOME}/Documents.tar.gz"
 	tar cvf Documents.tar.gz ~/Documents -I "gzip --best"
+}
+
+
+e() {
+	if [ "${EDITOR}" = "emacs" ] && [ "$(command -v emacsclient)" ]; then
+		emacsclient -a ${EDITOR} "$@" &
+	else
+		${EDITOR} "$@"
+	fi
 }
 
 
@@ -179,12 +189,11 @@ export UEBERZUG_FIFO=/tmp/ueberzug-fifo
 # LESS (for man pages)
 export LESS_TERMCAP_mb=$'\033[1;32m'
 export LESS_TERMCAP_md=$'\033[1;32m'
+export LESS_TERMCAP_so=$'\033[01;33m'
 export LESS_TERMCAP_me=$'\033[0m'
 export LESS_TERMCAP_se=$'\033[0m'
-export LESS_TERMCAP_so=$'\033[01;33m'
 export LESS_TERMCAP_ue=$'\033[0m'
 export LESS_TERMCAP_us=$'\033[1;4;31m'
-
 
 
 # Nix
