Cleaned up and added support for ksh

diff --git a/.config/shellconfig/main_rc b/.config/shellconfig/main_rc
--- a/.config/shellconfig/main_rc
+++ b/.config/shellconfig/main_rc
@@ -26,29 +26,62 @@ fi
 
 
 # PROMPT #
+# Guaranteed to work on dash, bash, zsh, and ksh
 print_prompt() {
 	ret=$?
-	dir_col=$'\033[38;5;11m'
-	success_col=$'\033[38;5;6m'
-	failed_col=$'\033[38;5;1m'
-	branch_col=$'\033[38;5;8m'
-	symbol=">"
-	if ! [ "${PWD#${HOME}*}" ]; then
-		printf '\001\033[1m\002\001%b\002%s' "${dir_col}" "~${PWD#${HOME}}"
-	else
-		printf '\001\033[1m\002\001%b\002%s' "${dir_col}" "${PWD}"
+	symbol="➜"
+	bold="\033[1m"
+	dir_col="\033[38;5;11m"
+	branch_col="\033[38;5;8m"
+	failed_col="\033[38;5;1m"
+	success_col="\033[38;5;6m"
+	reset="\033[0m"
+
+
+	if [ "${BASH}" ]; then
+		wrapper_start="\001"
+		wrapper_end="\002"
+	elif [ "${ZSH_NAME}" ]; then
+		wrapper_start="%{"
+		wrapper_end="%}"
+	elif ! [ "${KSH_VERSION}" ]; then
+		unset bold dir_col branch_col failed_col success_col reset
 	fi
+
+
+	if [ "${KSH_VERSION}" ] || { [ "${wrapper_start}" ] && [ "${wrapper_end}" ]; } ; then
+		bold="${wrapper_start}${bold}${wrapper_end}"
+		dir_col="${wrapper_start}${dir_col}${wrapper_end}"
+		branch_col="${wrapper_start}${branch_col}${wrapper_end}"
+		failed_col="${wrapper_start}${failed_col}${wrapper_end}"
+		success_col="${wrapper_start}${success_col}${wrapper_end}"
+		reset="${wrapper_start}${reset}${wrapper_end}"
+	fi
+
+
+	if ! [ "${PWD%${HOME}*}" ]; then
+		printf '%b%b%s' "${bold}" "${dir_col}" "~${PWD#${HOME}}"
+	else
+		printf '%b%b%s' "${bold}" "${dir_col}" "${PWD}"
+	fi
+
 
 	branch="$(git branch --show-current 2>&-)"
-	[ "${branch}" ] && printf '\001%b\002 [ %s ]' "${branch_col}" "${branch}"
+	[ "${branch}" ] && printf '%b [ %s ]' "${branch_col}" "${branch}"
+
 
 	if [ ${ret} -eq 0 ]; then
-		printf '\n\001%b\002%s \001\033[0m\002' "${success_col}" "${symbol}"
+		printf '\n%b%s%b ' "${success_col}" "${symbol}" "${reset}"
 	else
-		printf '\n\001%b\002%s \001\033[0m\002' "${failed_col}" "${symbol}"
+		printf '\n%b%s%b ' "${failed_col}" "${symbol}" "${reset}"
 	fi
 }
-export PS1="\$(print_prompt)"
+if [ "${BASH}" ] || [ "${ZSH_NAME}" ]; then
+	export PS1="\$(print_prompt)"
+else
+	export PS1="\$(print_prompt 1)"
+fi
+
 
 
 
@@ -64,11 +97,6 @@ alias mv="mv -i"
 alias rm="rm -i"
 alias cp="cp -i"
 alias ip="ip --color=auto"
-alias gscr='cd "${HOME}"/.config/scripts/; ls'
-alias grice='cd "${HOME}"/.local/rice; ls'
-alias makepkgmem="BUILDDIR=/tmp/makepkg makepkg"
-alias parumem="paru --clonedir /tmp/makepkg"
-alias sx='startx ${HOME}/.config/X11/xinitrc'
 
 
 
@@ -111,7 +139,7 @@ e() {
 }
 
 
-fet.sh() {
+fetsh() {
 	bin=$(command -v fet.sh)
 	if [ "${bin}" ]; then
 		url="https://github.com/6gk/fet.sh/raw/master/fet.sh"
