.bashrc: Cleanup

diff --git a/.config/shellconfig/main_rc b/.config/shellconfig/main_rc
--- a/.config/shellconfig/main_rc
+++ b/.config/shellconfig/main_rc
@@ -100,9 +100,11 @@ alias cp="cp -i"
 alias ip="ip --color=auto"
 alias dit="git --git-dir=${HOME}/.local/dots --work-tree=${HOME}"
 
+
+# FUNCTIONS #
 dra() {
 	if ! [ "$(command -v droidcam-cli)" ]; then
-		printf "[\033[1;31mERROR\033[0m] 'droidcam-cli' isn't installed\n" >&2
+		printf "\033[1;31m|\033[0m 'droidcam-cli' isn't installed\n" >&2
 		return 127
 	fi
 
@@ -112,10 +114,12 @@ dra() {
 				while sleep 1; do
 					[ "$(pidof droidcam-cli)" ] && break
 				done
-				printf "Loading alsa-module... "
-				pacmd load-module module-alsa-source device=hw:Loopback,1,0 &&
-					printf "\033[1;32m✓\033[0m\n" ||
-						printf "\033[1;31m✗\033[0m\n"
+				pacmd load-module module-alsa-source device=hw:Loopback,1,0
+				if [ ${?} = 0 ]; then
+					printf "\033[1;32m|\033[0m Loaded pulseaudio module\n"
+				else
+					printf "\033[1;31m|\033[0m Failed to load pulseaudio module\n"
+				fi
 			} &
 			break
 		fi
@@ -139,14 +143,14 @@ fix_time() {
 }
 
 
-jmtpfs-auto-mount() {
+jmtpfs_auto_mount() {
 	if ! [ "$(command -v jmtpfs)" ]; then
-		printf "[\033[1;31mERROR\033[0m] Command 'jmtpfs' not found\n" >&2
+		printf "\033[1;31m|\033[0m Command 'jmtpfs' not found\n" >&2
 		return 1
 	fi
 
 	if ! jmtpfs -l | { read _; read line; [ "${line}" ]; }; then
-		printf "[\033[1;31mERROR\033[0m] No devices found\n" >&2
+		printf "\033[1;31m|\033[0m No devices found\n" >&2
 		return 1
 	fi
 
@@ -162,9 +166,8 @@ jmtpfs-auto-mount() {
 
 sx() {
 	# Start x server
-	xinitrc="${HOME}/.config/X11/xinitrc "
-	if [ -f "${xinitrc}" ]; then
-		startx "${xinitrc}"
+	if [ -f "${HOME}/.config/X11/xinitrc " ]; then
+		startx "${HOME}/.config/X11/xinitrc "
 	else
 		startx
 	fi
@@ -197,11 +200,14 @@ fetch() (
 	fi
 
 	# Get the WM
-	wm=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK 2>&1)
-	wm=$(xprop -id "${wm##* }" -notype -len 100 -f _NET_WM_NAME 8t 2>&1)
-	wm=${wm%\"*}
-	wm=${wm##*\"}
-	[ "${wm}" ] || wm="Unknown"
+	if [ "${DESKTOP}" ] && [ "$(command -v xprop)" ]; then
+		wm=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK 2>&1)
+		wm=$(xprop -id "${wm##* }" -notype -len 100 -f _NET_WM_NAME 8t 2>&1)
+		wm=${wm%\"*}
+		wm=${wm##*\"}
+	else
+		wm="Unknown"
+	fi
 
 	# The username and hostname
 	name="\033[1;33m${USER}\033[0m@\033[33m${HOSTNAME}\033[0m\n"
