All hail Gruvbox

diff --git a/.config/shellconfig/main_rc b/.config/shellconfig/main_rc
--- a/.config/shellconfig/main_rc
+++ b/.config/shellconfig/main_rc
@@ -125,6 +125,40 @@ compress_documents() {
 }
 
 
+record() {
+	# Record desktop screen and desktop audio
+	if ! [ "${1}" ]; then
+		printf "[\033[1;31mERROR\033[0m]: Filename not provided\n" >&2
+		return 1
+	fi
+
+	if ! [ "$(pidof pulseaudio)" ]; then
+		printf "[\033[1;31mERROR\033[0m]: Pulseaudio isn't running\n" >&2
+		return 1
+	fi
+
+	for dep in "pactl" "ffmpeg"; do
+		[ "$(command -v ${dep})" ] && continue
+		printf "[\033[1;31mERROR\033[0m]: Command '${dep}' not found\n" >&2
+		return 1
+	done
+
+	tab=$(printf '\t')
+	source=$(pactl list short sources | { read line; printf '%s\n' "${line}"; })
+	source=${source#*${tab}}
+	source=${source%%${tab}*}
+	ffmpeg \
+		-f x11grab \
+		-framerate 30 \
+		-i :0.0 \
+		-f pulse \
+		-i "${source}" \
+		-preset ultrafast \
+		-crf 18 \
+		-pix_fmt yuv420p "${1}"
+}
+
+
 colors() {
 	i=0
 	printf '\n'
