Update, automatically remove songs that aren't in the playlist

diff --git a/.config/scripts/migrate/smeuesic b/.config/scripts/migrate/smeuesic
--- a/.config/scripts/migrate/smeuesic
+++ b/.config/scripts/migrate/smeuesic
@@ -1,75 +1,114 @@
 #!/bin/sh
-# ------------------------------------------------
-# Script Name    - smeuesic
-# Author Name    - Smeueg
-# Author Email   - Smeueg@gmail.com
-# Author Gitlab  - https://gitlab.com/Smeueg
-# Sun 20 Mar 12:01:39 WIB 2022
-# ------------------------------------------------
-# TODO:
-# Automatically remove files that aren't in the youtube playlist
-#
-#
-# Download the mp3 of videos in a playlist
-# Change the value `pl_url` to the playlist url that you want
-
-
 music_dir="${HOME}/Music"
-pl_url="https://www.youtube.com/playlist?list=PLRV1hc8TIW-7znQIWaVarxdUxf7lskmBc"
+if [ "${1}" ]; then
+	if [ "${pl_url%%https://www.youtube.com/playlist\?list=*}" ]; then
+		printf '[\033[1;31mERROR\033[0m] Invalid URL\n'
+		exit 1
+	fi
 
-# Check if youtube-dl is installed
-[ "$(command -v youtube-dl)" ] || {
-	printf '\033[1;31m[ERROR]\033[0m `youtube-dl` is not installed\n' >&2
+	pl_url=${1}
+
+else
+	pl_url="https://www.youtube.com/playlist?list=PLRV1hc8TIW-7znQIWaVarxdUxf7lskmBc"
+fi
+newline="
+"
+
+[ "${pl_url%%https://www.youtube.com/playlist\?list=*}" ] && echo "invalid url"
+
+
+if ! [ "$(command -v youtube-dl)" ]; then
+	printf "[\033[1;31mERROR\033[0m] 'youtube-dl' isn't installed. Exiting\n" >&2
 	exit 1
-}
+fi
 
-# A replacement for `sed`
-replace() { # Arguments: <string> <query> <substitution>
-	string="${1}"
-	query="${2}"
-	substitution="${3}"
 
-	while ! [ "${string%%*${query}*}" ]; do
-		string="${string%%${query}*}${substitution}${string#*${query}}"
+# Exit if "${music_dir}" doesn't exist and can't be created
+! [ -d "${music_dir}" ] &&
+	! mkdir -pv "${music_dir}" &&
+	exit 1
+
+
+
+replace() {
+	# Replace ${1} with ${2} in the variable ${3}
+	str=${3}
+	while ! [ "${str%%*${1}*}" ]; do
+	 	str="${str%%${1}*}${2}${str#*${1}}"
 	done
-	echo "${string}"
-}
-
-# Check if ${music_dir} exist as a directory
-[ -d "${music_dir}" ] || {
-	printf '\033[1;32m[NOTICE] "%s" does not exit, create? [Y\\n] ' "${music_dir}"
-
-	read input
-	case "${input}" in
-		[Yy][Ee][Ss]|[Yy]|"") ;;
-		*) printf 'Exiting...\n' && exit 1 ;;
-	esac
-	mkdir -pv "${music_dir}"
+	printf '%s\n' "${str}"
+	unset str
 }
 
 
-# Header
-len=$((COLUMNS / 2 - 7))
-while [ ${#str} -lt ${len} ]; do
-	str="${str}="
-done
-printf '%s Getting Urls %s' "${str}" "${str}"
+header() {
+	i=0
+	while [ ${i} -ne ${COLUMNS} ]; do
+		str="${str}─"
+		i=$((i+1))
+	done
+	printf '\033[1;31m%s\033[0m' "${str}"
+	[ "${1}" ] &&
+		printf "\r\033[$(((COLUMNS - ${#1} - 2) / 2))C ${1} \n"
+	unset str
+}
 
 
-# Downloading Music
-while read title; do
-	read id
-	title=$(replace "${title}" "/" "\\")
+get_title_id() {
+	youtube-dl "${pl_url}" --flat-playlist --get-id -e |
+		{
+			while { read -r title; read id; }; do
+				title=$(IFS="/" replace "\\" "${title}")
+				title=$(replace "/" "\\" "${title}")
+				tmp="${tmp}${title}:${id}${newline}"
+			done
+			printf '%s\n' "${tmp}"
+		}
+}
 
-	url="https://www.youtube.com/watch?v=${id}"
-	[ -f "${music_dir}/${title}.mp3" ] ||
-		youtube-dl "${url}" \
-		 		   -x \
-		 		   --audio-format mp3 \
-		 		   --add-metadata --metadata-from-title "%(title)s" \
-		 		   --postprocessor-args \
-		 		   "-acodec libmp3lame" \
-		 		   -o "${music_dir}/${title}.%(ext)s"
-done <<EOF
-$(youtube-dl ${pl_url} --flat-playlist  --get-id -e)
-EOF
+
+sync_download() {
+	# Download song's that aren't downloaded yet
+	header "Downloading Songs"
+	ran=false
+	for line in ${output}; do
+		title=${line%:*}
+		url="https://www.youtube.com/watch?v=${line##*:}"
+		if ! [ -f "${music_dir%/}/${title}.mp3" ]; then
+			ran=:
+		   	youtube-dl "${url}" \
+					   -x \
+		 			   --audio-format mp3 \
+		 			   --add-metadata --metadata-from-title "%(title)s" \
+		 			   --postprocessor-args \
+		 			   "-acodec libmp3lame" \
+		 			   -o "${music_dir}/${title}.%(ext)s"
+		fi
+	done
+	${ran} || printf 'No songs need to be downloaded\n'
+	header
+}
+
+
+sync_remove() {
+	# Remove song's that aren't in the playlist anymore
+	header "Removing Songs No Longer In The Playlist"
+	ran=false
+	for file in "${music_dir%/}"/*; do
+		file=${file#${music_dir%/}/}
+
+		for line in ${output}; do
+			[ "${line%:*}.mp3" = "${file}" ] && continue 2
+		done
+		ran=:
+		rm -v "${music_dir%/}/${file}"
+	done
+	${ran} || printf 'No files to remove\n'
+		header
+}
+
+
+output=$(get_title_id)
+IFS=${newline} sync_download
+printf '\n\n\n'
+IFS=${newline} sync_remove
